# Check if objects in image

# Goal definition
uint64 id
sensor_msgs/Image image

---
# Result definition
uint64 id
tut_common_msgs/BoundingBoxes boundingBoxes
sensor_msgs/Image image

---
# Feedback definition
